### ISSUE TITLE
Couldn't follow symbolic link

### ISSUE THREAD

**Issue by pocockn** [gschrader/ratpack-react-boilerplate#4]
I have attempted to get this project running but am stuck on one thing.

> index.html
> sym-linked, built from node

Thi doesn't seem to work, is there something special I have to do to copy the index file into my Ratpack resources? I am running Ubuntu

I have tried running this command from the root of my project to manually create the symlink.

`ln -s react-app/build/index.html site/src/ratpack/templates/index.html `

but I get the error below when I run a ./gradlew build or a ./gradlew clean build

> Could not list contents of /home/pocockn/dev/football/site/src/ratpack/templates/index.html Couldnt follow symbolic link

Thanks for the awesome project.

**Comment by gschrader** [comment]
I found that the git clone will create the links correctly (on macOS at least) I haven't tried Linux though (Windows didn't work for me). 

Maybe check the link from the template dir to see if it has the correct relative path.

```
~/github/gschrader/ratpack-react-boilerplate/ratpack/src/ratpack/templates master* glen@Glens-MacBook-Pro
❯ ls -al
total 8
drwxr-xr-x  3 glen  staff  102 Feb  9 10:17 .
drwxr-xr-x  5 glen  staff  170 Dec 13 12:29 ..
lrwxr-xr-x  1 glen  staff   34 Sep  2 18:09 index.html -> ../../../../react/build/index.html
```

**Comment by pocockn** [comment]
Ah ok, I don't have the same output as you.  How did you create the symlink in the first place? Maybe I can try that, rather than create my whole project again.  Thanks

**Comment by gschrader** [comment]
this should work, from the templates dir:

```
ln -s ../../../../react/build/index.html index.html
```

**Comment by pocockn** [comment]
That worked thanks, however I get 404's for my static files when I try access the index.html. I assume it should just work when I run ./gradlew run?

**Comment by gschrader** [comment]
When you say "access the index.html", do you mean hitting http://localhost:5050/ in the browser?

**Comment by pocockn** [comment]
Sorry I meant hitting the handler that has the render for my index.html

So i've created the symlink to a handlebars template and render it here

  ```
  handlers {
        get("admin") {
            render handlebarsTemplate("index.html")
        }
}
```

When I hit that handler I get a 404 on my static assets.

**Comment by gschrader** [comment]
Ah ok, so you would also need the static handler:

```
        get('static/:type/:id') { context ->
            def path = "/static/${context.pathTokens['type']}/${context.pathTokens['id']}"
            InputStream resourceStream = getClass().getResourceAsStream(path)
            if (resourceStream) {
                def contentType = context.get(MimeTypes).getContentType(path)
                context.response.send(contentType, resourceStream.bytes)
            } else {
                context.next()
            }
        }
```

You would also need to render the `index.html` from an all block depending on how you're handling your routing from the react side.

So I think something like this might work:

```
handlers {
      prefix("admin") {
        get('static/:type/:id') { context ->
            def path = "/static/${context.pathTokens['type']}/${context.pathTokens['id']}"
            InputStream resourceStream = getClass().getResourceAsStream(path)
            if (resourceStream) {
                def contentType = context.get(MimeTypes).getContentType(path)
                context.response.send(contentType, resourceStream.bytes)
            } else {
                context.next()
            }
        }

        all {
          render handlebarsTemplate("index.html")
        }
      }
}
```

**Comment by pocockn** [comment]
Thanks for the help but still getting the same 404's, here is my Ratpack.groovy file, can you see anything wrong in here?

 https://github.com/pocockn/football-prototype/blob/feature/react/site/src/ratpack/ratpack.groovy

 do you think it would be possible to create a gradle task that moves the static assets into my ratpack directory?

**Comment by gschrader** [comment]
I might have the static handler in the wrong spot it might need to be at the top level. You can use the developer tools in Chrome to confirm the path.
